CREATE SEQUENCE IF NOT EXISTS tasks_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE tasks
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    title      VARCHAR(255)                              NOT NULL,
    details    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    done       BOOLEAN                     DEFAULT FALSE NOT NULL,
    version    BIGINT                      DEFAULT 0     NOT NULL,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_tasks_done_created_at ON tasks (done, created_at);