-- Schema for TaskEntity (com.example.demo.tasks.entity.TaskEntity).
-- Run against an empty database:  psql -d task_api -f src/main/resources/db/schema.sql
-- ddl-auto=validate means Hibernate checks this schema at startup but never creates it.

BEGIN;

DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    -- @GeneratedValue(IDENTITY) maps to an identity column; Integer (not Long) in the
    -- entity, so integer rather than bigint keeps validate happy.
    id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      varchar(255) NOT NULL,
    details    varchar(255),
    created_at timestamptz  NOT NULL DEFAULT now(),
    -- primitive boolean can never be null, so NOT NULL matches the entity.
    done       boolean      NOT NULL DEFAULT false,
    -- @Version. Hibernate writes "UPDATE ... WHERE id = ? AND version = ?" and treats zero
    -- affected rows as a conflict, so this column is what makes a lost update detectable
    -- rather than silent. bigint to match the entity's Long.
    version    bigint       NOT NULL DEFAULT 0
);

-- Every list query filters on done and orders by created_at DESC, so this covers /done and
-- /pending both. (done, created_at DESC) and not a partial index: a partial one on "NOT done"
-- would serve /pending and leave /done unindexed.
CREATE INDEX idx_tasks_done_created_at ON tasks (done, created_at DESC);

COMMIT;
