BEGIN;

DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      varchar(255) NOT NULL,
    details    varchar(255),
    created_at timestamptz  NOT NULL DEFAULT now(),
    done       boolean      NOT NULL DEFAULT false,
    version    bigint       NOT NULL DEFAULT 0
);

CREATE INDEX idx_tasks_done_created_at_desc ON tasks (done, created_at DESC);
COMMIT;
